language: ruby
rvm:
- 2.5.0
cache: 
  - bundler
  - yarn
sudo: required
dist: trusty
services:
- postgresql
notifications:
  email: false
addons:
  chrome: stable
env:
  matrix:
  - TEST_FOLDER=controllers
  - TEST_FOLDER=decorators
  - TEST_FOLDER=features
  - TEST_FOLDER=models
  global:
  - secure: m32FNFRFa8S/AxJf6jHQ51vcuGyGrFf2S8yIgn5C9rtwzwlKVsar/HL4sjPc0y6ej0uP25QhgYCiw1+x4xePhe5TFRBtRbuv4tWC+4zbFqWTYwG4beDZsWmQYdlQRAwGLAb/WXSnTCE1uQS39yLjavl8MhhnpeC+3580CZMn4UQgyuKTCqZVW7rd9Y+Xvb2SjaQEr9hZyc6sMl1iCVhNCXBeT3Fx6DO2HfrwVNdju6/8+O06GXAgJY2hiEkvjS+ERHx+j6JOu1dcCX5QGOUUlE+pxSciVsT80XYG8ot/pONkDHdVBrmZDCUzLU5OcjU1dgWySHRiKjZKCJ2ruKWuKVidWKEDsYyO11Uc1KJYOBcIdnq+s4+NFK2JuSc2UVFnET9e684Cc2fT1755tCHMV5oiy7OqEWeBFRSDJwFLSx1mhBLwuPeh4CUH2YRJb9mpPUfWfasHS5FQRl5737IZ4dWb21zEQU43rRKvjXGQwF+rzf3lYd2Hr9kmQAhY8aej6dEE8zZOGS+y30snuH8GMShucxFFuYmYxIHXfAK2BHCd0YJRIuP9gLc9lMKdInmlowETTPE6stiZdc6pblS20a7aUDn6c7hgXhMcxrzYaLwaYMaDs58cl9qlfTjjm7h+ANi12qAOgBsHmO4mZqFFynKnZ7ylnRwueVBVdneezHU=
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rails assets:precompile
script:
- bundle exec rspec spec/$TEST_FOLDER
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "QVOhJVjUY4k+rJ5ZWjWl7SjW5r85338sR5pzMDTpQTmxRvV/62HKRnq0wsNfvNzJ9X6fWZlwK1r9OpjPgASYfoUzcS8cG3Jas0/tPg9fwoIekMpsL41Qmdp26HhGyX1f6gO7IR85t7rQlhvzT2pcYdjHdvfkAp9fdskUvzEjZVuhtVfJWOkiCMnhXT0UyKBuZlPCWSNKQ17hRWHRy332aSXBXMJGHqRw0E6NkL8NhPlD2mjhfxIFUkXjmzD5KuZeHDjASZWlBQrJkzOaX9SxL+iDozgDPK0HvU5zKIT5BVyZ1zCnP+MfN8Jobpmgq6R7AUDlec1wo8If7LAv9DbSgWLbbefZItoK4IwSjJqdi5cxRt9xs816aVlGxbFe1qjXsvFQ2YJ87vq9Mld9y2jH15q7r84ahlz4BM913J9EojEjQrYCA0dpvvuYhKHLiWruyND8u8tSKPFtnlHVIRmrw7xQ1zj0FjnDI6aZv1M/Dfzf2ftVSfgzpP6p0TiwlSSboei4oL4IhEqZ7a/hfjB3bxPkWGq0KBklgTwfM+UXiEtL2oPFt5VFvH9jBPwdNucN8GcP65KJqLs0QO0N88tVm//HQt2y5zoeA8iGImoEXivGxVuBdiwAzTzniUYx8GWBLLEC023+NJSXflpbL/9tNDetsoJh0I0QZd5nTj2wn0I="
  app: floating-tor-80170
  on:
    repo: leosoaivan/empower
